module Settings.Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/luis/Pictures/Wallpapers/Color Burst 3.jpg"

-- Special
background="#010102"
foreground="#cac3e7"
cursor="#cac3e7"

-- Colors
color0="#010102"
color1="#5055AF"
color2="#6352A1"
color3="#965EAD"
color4="#CE5AA4"
color5="#986DD1"
color6="#758AD3"
color7="#cac3e7"
color8="#8d88a1"
color9="#5055AF"
color10="#6352A1"
color11="#965EAD"
color12="#CE5AA4"
color13="#986DD1"
color14="#758AD3"
color15="#cac3e7"
